export const chapters = [
{'title': 'Greva din 1893 a minerilor englezi',
'subtitle': '',
'info': '„Sprawa Rabotnicza“,<br/>Paris, noiembrie-decembrie 1893.<br/>(Articol scris în limba poloneză)',
'idCh': '1.01',
},
{'title': 'Posibilism şi oportunism',
'subtitle': '',
'info': '„Sächsische Arbeiterzeitung“<br/>din 30 septembrie 1890',
'idCh': '1.02',
},
{'title': 'Cuvântări rostite la Congresul de la Stuttgart al Partidului social-democrat din Germania',
'subtitle': 'Cuvântări în cadrul discuţiei cu privire la problemele tacticii',
'info': 'Din procesul-verbal al dezbaterilor Congresului Partidului social-democrat din Germania<br/>Stuttgart, 3—8 octombrie 1898',
'idCh': '1.03',
},
{'title': 'O problemă de tactică',
'subtitle': '',
'info': '„Leipziger Volkszeitung“<br/>din 6 iulie 1899',
'idCh': '1.04',
},
{'title': 'Cuvântări rostite la Congresul de la Hanovra al Partidului social-democrat din Germania',
'subtitle': '',
'info': '„Procesul-verbal al dezbaterilor Congresului Partidului social-democrat din Germania“,<br/>Hanovra 9—14 octombrie 1899',
'idCh': '1.05',
},
{'title': 'Cucerirea puterii politice',
'subtitle': '',
'info': 'Din broşura „Sozialreform oder Revolution“<br/>(„Reformă socială sau revoluţie“),<br/>partea a II-a, capitolul 3,<br/>ediţia I, 1900',
'idCh': '1.06',
},
{'title': 'Revoluţia din Rusia',
'subtitle': '',
'info': '„Die Gleichheit",<br/>revistă pentru apărarea intereselor<br/>muncitoarelor, nr. 3,<br/>Stuttgart, 8 februarie 1905.',
'idCh': '1.07',
},
{'title': 'În lumina focului revoluţiei',
'subtitle': '',
'info': '„Sächsische Arbeiterzeitung“<br/>din 1 mai 1905',
'idCh': '1.08',
},
{'title': 'Rezolvarea problemei',
'subtitle': '',
'info': '„Die Gleichheit“,<br/>revistă pentru apărarea intereselor muncitoarelor,<br/>Stuttgart, 29 noiembrie 1905',
'idCh': '1.09',
},
{'title': 'Cuvântare rostită la Congresul de la Mannheim al Partidului social-democrat din Germania în cadrul dezbaterii cu privire la greva politică de masă',
'subtitle': '26 septembrie 1906',
'info': '„Procesul-verbal al dezbaterilor Congresului Partidului social-democrat din Germania“, Mannheim, 23—29 septembrie 1906',
'idCh': '1.10',
},
{'title': 'Cuvântare de salut rostită la Congresul de la Londra al P.M.S.D.R. ',
'subtitle': '16 mai 1907',
'info': 'Procesul-verbal al „Congresului de la Londra al P.M.S.D.R.“,<br/>editat de Comitetul Central. Paris, 1909<br/>(din limba rusă).',
'idCh': '1.11',
},
{'title': 'Cuvântare rostită la Congresul internaţional de la Stuttgart al socialiştilor în cadrul comisiei pentru problemele privind militarismul şi conflictele internaţionale',
'subtitle': '21 august 1907',
'info': 'Procesul-verbal al „Congresului internaţional de la Stuttgart al socialiştilor“<br/>18—24 august 1907.',
'idCh': '1.12',
},
{'title': 'Greva politică de masă şi sindicatele',
'subtitle': '1 octombrie 1910',
'info': 'Publicată pentru prima oară în „Der Propagandist“, publicaţie lunară editată de C.C. al P.C.G., 1930, nr. 10—11.',
'idCh': '1.13',
},
{'title': 'Greva politică de masă',
'subtitle': '22 iulie 1913',
'info': '„Vorwärts“ din 24 iulie 1913',
'idCh': '1.14',
},
{'title': 'Militarismul, războiul şi clasa muncitoare',
'subtitle': '20 februarie 1914',
'info': 'Publicată pentru prima oară în „Vorwärts"<br/>din 22 februarie 1914',
'idCh': '1.15',
},
{'title': 'Disciplină de partid',
'subtitle': '',
'info': '„Sozialdemokratische Korrespondenz“<br/>din decembrie 1914',
'idCh': '1.16',
},
{'title': 'Refacerea Internaţionalei',
'subtitle': '',
'info': '„Die Internationale“,<br/>nr. 1 din 1915',
'idCh': '1.17',
},
];